version: '3'
services:
  react-app:
    container_name: react_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'yarn && yarn start'
    ports:
      - "3000:3000"
    tty: true
