on:
  push:
    branches:
      - master

name: infra-bootcamp

jobs:
  grupo7:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
          with:
            sparse-checkout: .
      - name: Configure AWS credentinals
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Authentication
        run: aws eks update-kubeconfig --name eks-grupo0 --alias eks-grupo7 --region us-east-1
      - name: Get nodes
        run: kubectl get nodes
      - name: remove deployments
        run: kubectl delete deployment todo-app -n grupo7
      - name: apply deployments
        run: kubectl apply -f deployment.yaml
     
      
