on:
  push:
    branches:
      - master

name: infra-bootcamp

jobs:
  grupo7:
    runs-on: milbertc/todo-app
    steps:
      - name: Configure AWS credentinals
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}